### ISSUE TITLE
Bregma-lambda pitch?

### ISSUE THREAD

**Issue by chris-angeloni** [petersaj/neuropixels_trajectory_explorer#4]
The CCF atlas is rotated 5 degrees nose-down (as noted in the wiki). In the explorer, the brain also seems to be rotated similarly, nose-down slightly. I wanted to check whether this rotation is accounted for when the trajectory explorer generates coordinates/angles for surgical use.

Given that my lab levels lambda and bregma during surgery, do I need to add or subtract 5 degrees in elevation when using the trajectory explorer?

**Comment by petersaj** [comment]
Hi Chris - the angles on the trajectory explorer are relative to leveled bregma-lambda, so all coordinates should be used as-is if you're leveling bregma-lambda during surgery.

To clarify where the tilt comes from: since the CCF was created using only brains and not with reference to the skull, the CCF has an arbitrary tilt relative to the skull. From some recent work, that tilt was empirically estimated to be 5 degrees relative to a level bregma-lambda. The trajectory explorer takes this into account by tilting the CCF and giving all angle measurements relative to the tilted CCF.

**Comment by chris-angeloni** [comment]
Great, maybe this would be a useful note to add to the wiki page addressing the atlas!

**Comment by petersaj** [comment]
I tried clarifying on the wiki page, hopefully this makes it clearer? https://github.com/petersaj/neuropixels_trajectory_explorer/wiki/CCF-stereotax-coordinate-conversion
